eureka:
  instance:
    hostname: localhost
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true         
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8767/eureka

    
    
