server:
  port: 10007
spring:
  application:
    name: gateway-service           
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: im-marketings
        uri: lb://im-marketings
        predicates:
        - Path=/imm/**
       # filters:
       # - RewritePath=/imm/(?<path>.*), /$\{path}
      - id: report-generator
        uri: lb://report-generator
        predicates:
        - Path=/generate-report/**
       # filters:
       # - RewritePath=/generate-report/(?<path>.*), /$\{path}
      - id: auth-service
        uri: lb://ath
        predicates:
        - Path=/ath/**
       # filters:
       # - RewritePath=/auth/(?<path>.*), /$\{path}
