server:
  port: 10002
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///home/alaeddine/pfe/my-config
management:
  endpoints:
    web:
      exposure:
        include: "*"
