server:
  port: 10002
spring:
  cloud:
    config:
      server:
        git:
#          uri: ${user.dir}/im-configuration 
          uri: https://github.com/alaedin/im-configuration
      
management:
  endpoints:
    web:
      exposure:
        include: "*"

#spring.cloud.config.server.git.uri